### ISSUE TITLE
Not accepting Y

### ISSUE THREAD

**Issue by SyedWasiHaider** [andyharney/pySignare#1]
![error](https://cloud.githubusercontent.com/assets/3202990/6050518/3d1bbc7e-ac8e-11e4-8401-590e65d4751d.PNG)

Just tried to get this work on my windows 8 machine but it doesn't get past this line. I type Y and pressed enter and got the above picture.

**Comment by andyharney** [comment]
Hi Syed,

Could you confirm your Java and Python versions. I'm having trouble replicating the error with Java 1.8 and Python 3.4.2(x64). I've added in an exception to catch NameErrors and to continue with a warning.
Could you redownload and try again?

Thanks,
