### ISSUE TITLE
[Change Request] Return to menu

### ISSUE THREAD

**Issue by Testato** [andyharney/pySignare#2]
Your tool is very good, thanks for it.

Actually if you must sign and zipalign, you must start the .py, confirm by Yes, arrive to Menu and "sign" the apk.
After you must re-start the .py, re-confirm by Yes, re-arrive to menu and "zipalign".

Specially during development you will do this many times. 
It is better that when you "sign", the tool do not exit but return to menu, also after the Zipalign.
Return to menu until the user close the tool (by writing exit on the tool, or by close the window).

What do you think ?

**Comment by andyharney** [comment]
Hi @Testato 
Unfortunately I no longer work on this or Android.
You're welcome to fork it and give it a go 😄 

Thanks for finding it useful.

**Comment by Testato** [comment]
i do not know python, mmmm, but i can learn :-)
if i will work on it i prefer create a multi-platform GUI.
Do you know if somebody already wrote a GUI for it ?

**Comment by andyharney** [comment]
Not of the top of my head. 
If you head over to XDA-Developers, and take a look there. I'm sure someone would have.

Best of luck.
